

project_id = "luhhnsvwtnmxztcmdxyq"

[functions.create-order-token]
verify_jwt = false

[functions.get-order-token]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.get-shop-config]
verify_jwt = false

[functions.get-shop-bankdata]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

