// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luhhnsvwtnmxztcmdxyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1aGhuc3Z3dG5teHp0Y21keHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzM1NzYsImV4cCI6MjA2NTc0OTU3Nn0.wSCLJr4k6SNz4HLteqzJ6XJZ3SXBNIlXUx5V9XWyDyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);